### ISSUE TITLE
[feature request] Write trace URL for the build to the github PR that triggered it as a comment.

### ISSUE THREAD

**Issue by maplebed** [honeycombio/buildevents-orb#10]
When the build runs, `buildevents` can output a URL that will take you directly to the trace representing the build. It would be lovely to paste this back to the github PR that triggered the build.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
